### ISSUE TITLE
[Add Circle Request] MS护肤拼单群

### ISSUE THREAD

**Issue by linningmii** [Yat3s/Life-Balance#100]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS护肤拼单群

### Circle picture(width:height = 2:1)
![1](https://user-images.githubusercontent.com/14858674/199722796-87024b36-2d0e-4851-bb4a-e317d52ee580.jpg)

### Tags
拼单/护肤/面包/辣白菜

### City(Optional)
苏州/北京/上海

### Description(Optional, rich-text supported)
除了护肤品，还拼面包和辣白菜，只要你想，就有

**Comment by Yat3s** [comment]
Close as added.
