### ISSUE TITLE
[Add Circle Request] MS Pokemon 🍊🍇

### ISSUE THREAD

**Issue by ermaoermao** [Yat3s/Life-Balance#103]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Pokemon 🍊🍇

### Circle picture(width:height = 2:1)
![maxresdefault](https://user-images.githubusercontent.com/113008615/202589600-b107fb60-7bd8-4ad7-b455-29369339eed7.jpg)

### Tags
游戏

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
宝可梦朱紫

**Comment by Yat3s** [comment]
Close as added.
