### ISSUE TITLE
[Add Circle Request] MS Keyboard Lover

### ISSUE THREAD

**Issue by Chris-Yen68** [Yat3s/Life-Balance#105]
# You must know!
Please invite admin(Wechat ID: **ChrisJhen68**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Keyboard Lover

### Circle picture(width:height = 2:1)
![D3DA7C6C-6C1F-4D2E-8848-A046FBC57D05](https://user-images.githubusercontent.com/25418422/202617326-6e2ffc11-b503-4f69-b4e2-33357f732d78.jpeg)

### Tags
设备

### City(Optional)
[苏州/北京/上海]

**Comment by Yat3s** [comment]
Close as added.
