### ISSUE TITLE
[Add Circle Request] MS Goose Goose Duck

### ISSUE THREAD

**Issue by KelaKing** [Yat3s/Life-Balance#106]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Goose Goose Duck

### Circle picture(width:height = 2:1)
![capsule_616x353](https://user-images.githubusercontent.com/13584044/208222334-800e723a-9e1c-49aa-955c-151d11932f3c.jpg)

### Tags
游戏

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
你是鹅，还是鸭？一款社交推理游戏，你和你的同伴必须合作完成你的任务。请注意那些恶意的野鸭和其他鸟类，它们已经渗透到你的团队中，并将不惜一切代价来阻止你。

### Picture for promotion(Optional)
![Goose_Goose_Duck_Story_Trailer webm](https://user-images.githubusercontent.com/13584044/208222859-d27dc39a-a7c7-42d5-b801-945b38c6030e.jpg)
![maxresdefault](https://user-images.githubusercontent.com/13584044/208222909-e7500da4-2936-4b91-9df7-60f51f170551.jpg)

**Comment by Yat3s** [comment]
Close as added.
