### ISSUE TITLE
[Add Circle Request] MS  东百老乡群

### ISSUE THREAD

**Issue by donzoru** [Yat3s/Life-Balance#107]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS 东百老乡群

### Circle picture(width:height = 2:1)
![image](https://user-images.githubusercontent.com/16695393/208852475-0c10fa5e-e4be-4b53-a368-b58799207959.png)

### Tags
美食

### City(Optional)
苏州/北京/上海

### Description(Optional, rich-text supported)
东百老乡聚集地（东三省+内蒙古呼伦贝尔市、兴安盟、赤峰市、通辽市）找最地道的东北馆子

**Comment by Yat3s** [comment]
Close as added.
