### ISSUE TITLE
[Add Circle Request] MS Apex

### ISSUE THREAD

**Issue by ThenAndNoThen** [Yat3s/Life-Balance#108]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Apex

### Circle picture(width:height = 2:1)
![屏幕截图 2023-02-17 220750](https://user-images.githubusercontent.com/18694698/219677788-ba07b299-3fd5-40e6-bc72-8d32a288b2e4.png)

### Tags
游戏/端游

### City(Optional)
苏州/北京/上海

### Description(Optional, rich-text supported)
一起来打派吧！

**Comment by Yat3s** [comment]
Close as added.
