### ISSUE TITLE
上海紫竹羽毛球&网球

### ISSUE THREAD

**Issue by yezhu6** [Yat3s/Life-Balance#109]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
上海紫竹羽毛球&网球

### Circle picture(width:height = 2:1)
![2560x2560](https://user-images.githubusercontent.com/92571997/220258530-6befc72c-98ac-4aea-9046-6da0d8855342.jpg)

### Tags
[上海/紫竹/羽毛球/网球]

### City(Optional)
[上海]

### Description(Optional, rich-text supported)
羽毛球，网球爱好者聚集地

**Comment by yezhu6** [comment]
@Yat3s How long will the circle onboard usually take, please?

**Comment by Yat3s** [comment]
Close as added.
