### ISSUE TITLE
MS上海台球俱乐部

### ISSUE THREAD

**Issue by DavidYu-m** [Yat3s/Life-Balance#110]
### Circle name(displayed on Life Balance)
shzz桌球大联盟

### Circle picture(width:height = 2:1)
![1](https://user-images.githubusercontent.com/104286974/225518656-ea240496-3480-4362-a951-bf8f5c62831d.png)

### Tags
体育/运动/竞技

### City(Optional)
上海

### Description(Optional, rich-text supported)
以球会友

**Comment by Yat3s** [comment]
Close as added.
