### ISSUE TITLE
[Add Circle Request] MS 北京二手交易群

### ISSUE THREAD

**Issue by xhywxtt** [Yat3s/Life-Balance#111]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS二手交易群

### Circle picture(width:height = 2:1)
[Circle picture](https://my.visualstudio.com/Benefits)

### Tags
二手/闲置

### City(Optional)
北京

### Description(Optional, rich-text supported)
买买买！卖卖卖！

**Comment by Yat3s** [comment]
Close as added.
