### ISSUE TITLE
MS苏州跑步爱好群

### ISSUE THREAD

**Issue by yzheng347** [Yat3s/Life-Balance#112]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS苏州跑步爱好群

### Circle picture(width:height = 2:1)
[Circle picture]
![D4E4A127-17E4-4220-B0D2-C4749E1C9C91](https://user-images.githubusercontent.com/25203742/230378090-442bff37-8835-4565-816c-9bafaef0f74d.jpeg)

### Tags
(eg. 游戏/美食)
苏州/运动/健身

### City(Optional)
[苏州/北京/上海]
苏州

### Description(Optional, rich-text supported)
(e.g. 这个是一个神奇的小圈子)
这是一个马拉松爱好者的社交群，平时周末大家也可以一起约休闲跑～

**Comment by Yat3s** [comment]
Close as added.
