### ISSUE TITLE
[Add Circle Request] MS Star Rail

### ISSUE THREAD

**Issue by alicema** [Yat3s/Life-Balance#113]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Star Rail

### Circle picture(width:height = 2:1)

![chs-1-1920x1080-fc7b851d808b](https://user-images.githubusercontent.com/10561178/233901097-93cf2c82-cd28-447a-b72e-8bc319c5774e.jpg)

### Tags
游戏 米哈游 星穹铁道

### Description(Optional, rich-text supported)
愿此行，终抵群星

**Comment by Yat3s** [comment]
Close as added.
