### ISSUE TITLE
[Add Circle Request]  MS 以茶会友

### ISSUE THREAD

**Issue by Yixian15** [Yat3s/Life-Balance#115]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)

MS 以茶会友

### Circle picture(width:height = 2:1)

![_9557b79d-844d-4e65-a72b-34a6e2d4bc86](https://github.com/Yat3s/Life-Balance/assets/11811103/efe3d727-3fa0-4361-9cd0-7a3473b9aa92)

### Tags

美食/喝茶

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)

喝茶交友

**Comment by Yat3s** [comment]
Close as added.
