### ISSUE TITLE
[Add Circle Request] MS户外社

### ISSUE THREAD

**Issue by Continent7** [Yat3s/Life-Balance#117]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request
Done. 

### Circle name(displayed on Life Balance)
MS户外社

### Circle picture(width:height = 2:1)
![c544a2c682b2ca1fe8a577a5c263eb1](https://github.com/Yat3s/Life-Balance/assets/33411616/ab305db3-ed0e-4447-b7e6-af661cd050b1)

### Tags
户外

### City(Optional)
上海/无锡

### Description(Optional, rich-text supported)
上海MS户外社

**Comment by Yat3s** [comment]
Close as added.
