### ISSUE TITLE
[Add Circle Request] MS Diablo

### ISSUE THREAD

**Issue by zetasq** [Yat3s/Life-Balance#118]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Diablo

### Circle picture(width:height = 2:1)
![d4-open-graph_001](https://github.com/Yat3s/Life-Balance/assets/919184/2c624251-1e6c-4ba4-9ae0-bf4615a29730)

### Tags
游戏

### City(Optional)
Sanctuary

### Description(Optional, rich-text supported)
Meet your maker, farm for fame.

**Comment by Yat3s** [comment]
Close as added.
