### ISSUE TITLE
[Add Circle Request] Circle name

### ISSUE THREAD

**Issue by yifan-zhou922** [Yat3s/Life-Balance#119]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS紫竹乒乓球

### Circle picture(width:height = 2:1)
<img width="940" alt="image" src="https://github.com/Yat3s/Life-Balance/assets/78060542/2bcc967f-a464-4b7c-a49d-cb5813f527b1">
### Tags
运动/体育/乒乓球

### City(Optional)
上海

### Description(Optional, rich-text supported)
乒乓球爱好者

**Comment by Yat3s** [comment]
Close as added
