### ISSUE TITLE
[Add Circle Request] MS Arknights

### ISSUE THREAD

**Issue by ziqch** [Yat3s/Life-Balance#120]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Arknights

### Circle picture(width:height = 2:1)
![Snipaste_2023-07-22_15-05-59](https://github.com/Yat3s/Life-Balance/assets/23625182/aef68984-a5ab-4c8b-b4cd-4c8ea499c99d)

### Tags
(eg. 游戏/明日方舟/Arknights)

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
刀客塔，您还有许多事情需要处理。现在还不能休息哦~

**Comment by Yat3s** [comment]
Close as added
