### ISSUE TITLE
[Add Circle Request] MS Helldiver

### ISSUE THREAD

**Issue by ms-henglu** [Yat3s/Life-Balance#140]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Helldivers

### Circle picture(width:height = 2:1)
![image](https://github.com/Yat3s/Life-Balance/assets/79895375/d5f5f5bd-407e-428f-8575-4fd92580e844)

### Tags
游戏

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
Enlist in the Helldivers and join the fight for freedom across galaxy!

**Comment by Yat3s** [comment]
@ms-henglu Could you add Wechat `4645643`?
