### ISSUE TITLE
[Add Circle Request] MS Golfer 

### ISSUE THREAD

**Issue by Lucidedream** [Yat3s/Life-Balance#141]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS Golfer

### Circle picture(width:height = 2:1)
![images](https://github.com/Yat3s/Life-Balance/assets/6936598/02750ef2-280a-4feb-9848-8640c6d59041)

### Tags
体育/健身

### City(Optional)
苏州

### Description(Optional, rich-text supported)
Golf is hard... 欢迎大家来讨论自己的经验、技巧，以及那些令人难忘的瞬间

**Comment by Yat3s** [comment]
Hi @Lucidedream Could you add Wechat `4645643`?

**Comment by Lucidedream** [comment]
added, thanks for the reminder.
