### ISSUE TITLE
[Add Circle Request] MS潮汕老乡群

### ISSUE THREAD

**Issue by sodacorsair** [Yat3s/Life-Balance#145]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
 MS潮汕老乡群

### Circle picture(width:height = 2:1)
![Untitled](https://github.com/Yat3s/life-balance/assets/31685234/eb8d0c75-8182-4fff-843d-0f1049061905)

### Tags
内部交流

### City(Optional)
[不限]

### Description(Optional, rich-text supported)
MS潮汕

**Comment by Yat3s** [comment]
@sodacorsair Could you add Wechat id **4645643** then invite them into your group?

**Comment by sodacorsair** [comment]
> @sodacorsair Could you add Wechat id **4645643** then invite them into your group?

Have added, search the group name: MS潮汕老乡群.

**Comment by Yat3s** [comment]
@sodacorsair Hi, you should send a message in that group to active it, otherwise, others are unable to see it
