### ISSUE TITLE
[Group Indexing Request] MS LOL Mobile

### ISSUE THREAD

**Issue by yiz132** [Yat3s/Life-Balance#17]
- [X] This group only serves Microsoft
- [X] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS LOL Mobile

### Group icon(File or link, only `.png` supported)**
![lolm](https://user-images.githubusercontent.com/50721552/138659810-c6a3bac5-ef11-423c-bc86-07059df6e035.png)

**Comment by Yat3s** [comment]
Close as indexed
