### ISSUE TITLE
[Group Indexing Request]  MS一起去livehouse

### ISSUE THREAD

**Issue by Senerer** [Yat3s/Life-Balance#19]
- [x] This group only serves Microsoft
- [ ] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
  MS一起去livehouse

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)**

![8db8bac74a6c4a09e316e6081b0f756](https://user-images.githubusercontent.com/37288369/139253253-9f845772-428e-4c8e-a658-39b88c067f50.jpg)
)

**Comment by Yat3s** [comment]
Close as indexed
