### ISSUE TITLE
[Group Indexing Request] MS Suzhou Billiards and Snooker Lover

### ISSUE THREAD

**Issue by zhzho1995** [Yat3s/Life-Balance#24]
- [x] This group only serves Microsoft
- [ ] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS Suzhou Billiards and Snooker Lover

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)**
![icon](https://pic.ntimg.cn/file/20150505/11284670_154733526000_2.jpg)

**Comment by Yat3s** [comment]
Close as indexed
