### ISSUE TITLE
[Group Indexing Request] MS Suzhou ACMer and OIer

### ISSUE THREAD

**Issue by zhzho1995** [Yat3s/Life-Balance#25]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS Suzhou ACMer and OIer

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)**
![icon](https://upload.wikimedia.org/wikipedia/en/1/1d/ICPC_International_Collegiate_Programming_Contest_logo%2C_Aug_2018.png)

**Comment by Yat3s** [comment]
Close as indexed
