### ISSUE TITLE
[Group Indexing Request] MS 画匠 - 微软绘画爱好者

### ISSUE THREAD

**Issue by nonemaw** [Yat3s/Life-Balance#26]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS 画匠

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)**
![3416688](https://user-images.githubusercontent.com/8576808/139628024-533fb9d1-7596-4314-bc00-9636ed26e448.png)

**Comment by Yat3s** [comment]
Close as indexed
