### ISSUE TITLE
[Group Indexing Request] MSReading

### ISSUE THREAD

**Issue by guojms** [Yat3s/Life-Balance#28]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
Group name MSReading

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)**
![image](https://user-images.githubusercontent.com/87634713/140251010-a5c6252b-7f75-4efd-9d12-171522e0c54b.png)

**Comment by Yat3s** [comment]
Close as indexed
