### ISSUE TITLE
[Group Indexing Request] 剧本杀交流组队群

### ISSUE THREAD

**Issue by fondoger** [Yat3s/Life-Balance#29]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
剧本杀交流组队群  
msgdetectives

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![](https://img.ixintu.com/download/jpg/20201226/561c4564fce40f01025b8b86247f16fb_512_512.jpg!ys)

### Picture for promotio
![WeChat Image_20211104155051](https://user-images.githubusercontent.com/22270677/140276644-00add17c-981a-4f35-b26f-4aa481a79a83.jpg)
n

**Comment by Yat3s** [comment]
@fondoger Could you upload a picture for promotion? Thanks

**Comment by Yat3s** [comment]
Close as indexed.
