### ISSUE TITLE
[Group Indexing Request] MS 滑板群

### ISSUE THREAD

**Issue by nbystndr** [Yat3s/Life-Balance#30]
- [x] This group only serves Microsoft
- [ ] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS 滑板群

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![oly_picto_jpeg-skateboarding](https://user-images.githubusercontent.com/9493961/140272762-148dd540-f937-41a4-97bf-ecc8aadd9e22.jpg)

### Picture for promotion
![skateboarding-g988f05570_1920](https://user-images.githubusercontent.com/9493961/140274726-98a199ca-b6d1-4a5a-a9af-6e0abf2bdf0b.jpg)

**Comment by nbystndr** [comment]
@Yat3s Pls ask coconut to join the chat via link I sent to her. 😀

**Comment by Yat3s** [comment]
Close as indexed.
