### ISSUE TITLE
[Bug] Unable to dismiss activity QR code dialog

### ISSUE THREAD

**Issue by nandin-borjigin** [Yat3s/Life-Balance#35]
**Describe the bug**
Unable to dismiss activity QR code dialog. Clicking/Tapping on the close button (cross icon) have no effect.

**Screenshots**
![image](https://user-images.githubusercontent.com/10903833/141054716-cce835d0-5e10-432e-ac8b-f5502b4b50cc.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.1
 - WeChat: 8.0.16
 
 - Device: Desktop PC
 - OS: Windows 11 (Build 22500.1000)
 - WeChat: 3.4.0.38

**Comment by Yat3s** [comment]
Close as fixed
