### ISSUE TITLE
Wework parking space booking

### ISSUE THREAD

**Issue by Yat3s** [Yat3s/Life-Balance#36]
Wework 停车位预订规则：

1.只有在清单内的100个车牌才可预订 Wework 的50个停车位。
2.预订时间：提前1个工作日；取消时间：每个工作日的9:00前。
3.预订需填写信息：Alias、车牌号（车牌号仅限在清单内的100个）。
4.排队功能。如果50个停车位预订已满，其他人可以排队等候，一旦有人取消，则依次替补。
5.通知功能。预订成功、取消成功、排队成功的用户可收到通知（邮件或微信小程序通知）。
6.管理员权限。管理员可获取当天预订成功的清单，包含Alias、车牌号信息。
7. 凌晨 0 点抢第二天的车位。

Wework parking reservation rules:

1.The Wework 50 parking lots can be reserved by the 100 license plates within the list on a first-come, first-served basis.

2.Reserve time: 1 working day in advance. Cancellation time: before 9:00 a.m. of the working day.

3.The information that is required when reserving a Wework parking lot includes: Alias, license plate number (within the list).

4.Waiting List. When Wework 50 parking lots registration is full, a waiting list will be created automatically. Employees on the waiting list will automatically be enrolled once a spot becomes available.

5.Notification. Once reserved, cancelled, substituted successfully they will receive a notification (email or Wechat).

6.Administrator. The administrator has the access to review the reservation list.

**Comment by nandin-borjigin** [comment]
涉及到资源分配的策略需要一个权利来维持，不然破坏游戏规则的人永远是获利的

**Comment by Yat3s** [comment]
Close as implemented
