### ISSUE TITLE
[Group Indexing Request] SHZZ 桌游社

### ISSUE THREAD

**Issue by Iamanorange** [Yat3s/Life-Balance#40]
- [X] This group only serves Microsoft
- [X] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
SHZZ 桌游社
提议 #msgboardgame_shzz

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
复用苏州群
### Picture for promotion
复用苏州群

因桌游常有线下活动，有地区分群很合理。
这个群是今年夏天REF建的，目前246人。

**Comment by Yat3s** [comment]
Close as indexed.
