### ISSUE TITLE
[Group Indexing Request] SHZZ 剧本杀

### ISSUE THREAD

**Issue by Iamanorange** [Yat3s/Life-Balance#41]
- [X] This group only serves Microsoft
- [X] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
SHZZ 剧本杀
提议 #msgdetectives_shzz

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
复用苏州群
### Picture for promotion
复用苏州群

因剧本常有线下活动，有地区分群很合理。
今年秋天由爱好者自发建群，目前34人。

**Comment by Yat3s** [comment]
Close as indexed.
