### ISSUE TITLE
[Group Indexing Request] MS Musicians

### ISSUE THREAD

**Issue by Joouis** [Yat3s/Life-Balance#47]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS Musicians

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![icon](https://user-images.githubusercontent.com/8896124/144542341-83fccf97-3e44-4f75-a96c-cda298cba6a6.jpeg)

### City
It works for all locations online.

**Comment by Joouis** [comment]
@Yat3s Thanks for indexing. Can you help to change this new group icon? It's my bad that ignored the actual look on the phone, too weird to take one more glance 😢 .

![icon](https://user-images.githubusercontent.com/8896124/146956124-438fb783-236b-4c2d-b818-1a1e43615730.png)

**Comment by Yat3s** [comment]
@Joouis Done.

**Comment by Yat3s** [comment]
Close as indexed.
