### ISSUE TITLE
[Group Indexing Request] Swift社区炒股协会

### ISSUE THREAD

**Issue by AnyuMSFT** [Yat3s/Life-Balance#48]
- [ ] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
Swift社区炒股协会

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![0119A992-D2FC-4A76-900F-CD0A60209402](https://user-images.githubusercontent.com/95017535/144855655-6e50aa0b-9c61-464a-ac94-746b93e31e4d.jpeg)

### City
[苏州/北京/上海]

### Picture for promotion(Optional)
![D545789C-BF4A-45D5-9A94-646C5639916C](https://user-images.githubusercontent.com/95017535/144856176-9896c127-ea7d-453b-a524-e0423c187b96.jpeg)

**Comment by Yat3s** [comment]
Close as not meet requirements
