### ISSUE TITLE
[Group Indexing Request] MS帝国时代

### ISSUE THREAD

**Issue by yiz132** [Yat3s/Life-Balance#49]
- [X] This group only serves Microsoft
- [X] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS帝国时代

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
[[Group icon]](https://www.google.com.hk/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fen%2F0%2F08%2FAge_of_Empires_IV_Cover_Art.png&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FAge_of_Empires_IV&tbnid=SNdKYg2KHM0S8M&vet=12ahUKEwiVoJv7ue30AhVwxqACHbu1B4MQMygAegUIARClAQ..i&docid=SPqxlkk0fiPPeM&w=320&h=400&itg=1&q=帝国时代4&client=safari&ved=2ahUKEwiVoJv7ue30AhVwxqACHbu1B4MQMygAegUIARClAQ)

### City
[苏州/北京/上海]

**Comment by Yat3s** [comment]
Close as indexed.
