### ISSUE TITLE
[Group Indexing Request] Your group name

### ISSUE THREAD

**Issue by formulahendry** [Yat3s/Life-Balance#50]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
巨硬上海 吃喝玩乐.Life

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
复用苏州吃喝玩乐群

### City
[闵行/上海]

**Comment by Yat3s** [comment]
Close as indexed.
