### ISSUE TITLE
[Group Indexing Request] MS Movie 🎞

### ISSUE THREAD

**Issue by shijieyao** [Yat3s/Life-Balance#52]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS Movie 🎞

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![movie](https://user-images.githubusercontent.com/22251154/147669933-9f727ae5-516e-4ce7-8b4e-c7154302fe9b.png)

### City
苏州

**Comment by Yat3s** [comment]
Close as indexed
