### ISSUE TITLE
[Group Indexing Request] MS 游泳🏊🏻

### ISSUE THREAD

**Issue by educated2022** [Yat3s/Life-Balance#53]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
MS 游泳🏊🏻

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![icon](https://user-images.githubusercontent.com/96809984/148012299-e94bee84-5757-409f-80b9-177df87f286c.jpg)

### City
苏州

**Comment by Yat3s** [comment]
Close as indexed
