### ISSUE TITLE
[Group Indexing Request] MS 期权&股票量化交易

### ISSUE THREAD

**Issue by HumphreyHao** [Yat3s/Life-Balance#54]
- [] This group only serves Microsoft
- [] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
[MS 期权&股票量化交易]

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
[[![73kJw6.jpg](https://s4.ax1x.com/2022/01/14/73kJw6.jpg)](https://imgtu.com/i/73kJw6)]

### City
[上海]

**Comment by Yat3s** [comment]
Close as indexed
