### ISSUE TITLE
[Group Indexing Request] Beijing 桌游社

### ISSUE THREAD

**Issue by LinMu7177** [Yat3s/Life-Balance#55]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
Beijing 桌游社

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
[Group icon]
![image](https://user-images.githubusercontent.com/43174767/149458189-e44d641f-c86d-4d1d-b9d7-ece0a0223c88.png)

### City
[北京]

**Comment by Yat3s** [comment]
Close as indexed
