### ISSUE TITLE
[Group Indexing Request] MS 上海租房

### ISSUE THREAD

**Issue by Iamanorange** [Yat3s/Life-Balance#56]
- [ ] This group only serves Microsoft
- [X] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
[MS 上海租房]

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![image](https://user-images.githubusercontent.com/6018925/150068964-6e7039a2-8395-47e8-bafd-9b32aea69fb7.png)
https://docs.microsoft.com/en-us/windows/apps/design/style/images/segoe-mdl/ec06.png

### City
[上海]

**Comment by Yat3s** [comment]
Close as indexed
