### ISSUE TITLE
[Group Indexing Request] 微软 星际争霸

### ISSUE THREAD

**Issue by Anduin2017** [Yat3s/Life-Balance#57]
- [x] This group only serves Microsoft
- [x] Invite **i-coconut** to group

### Group name(displayed on Life Balance)
微软 星际争霸

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![4f6bda1fded207b91c31f0cb5373803](https://user-images.githubusercontent.com/19531547/150079178-86b086a0-f21b-458c-ad51-176db7e7da6b.jpg)

### City
[苏州/北京/上海]

**Comment by Yat3s** [comment]
Close as indexed
