### ISSUE TITLE
[Group Indexing Request] MS 欢乐钓鱼群

### ISSUE THREAD

**Issue by xuhaoruins** [Yat3s/Life-Balance#58]
Please ensure the following requirements before raising your request
- [ ] This group only serves Microsoft
- [ ] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
[Group name]
MS 欢乐钓鱼群

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
[Group icon]
![fishing](https://user-images.githubusercontent.com/4555094/150291174-de0bef02-f464-420a-a506-88bed35dcd25.jpg)

### City
[苏州/北京/上海]
All

**Comment by Yat3s** [comment]
Close as indexed
