### ISSUE TITLE
[Group Indexing Request] MSGame-OverWatch

### ISSUE THREAD

**Issue by miku1958** [Yat3s/Life-Balance#59]
Please ensure the following requirements before raising your request
- [x] This group only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
[Group name]OverWatch

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
[Group icon]
https://blz.nosdn.127.net/1/fsbnet/logo-ow.png

### City
[苏州/北京/上海]

**Comment by Yat3s** [comment]
@miku1958 Please invite admin(Wechat ID: 4645643) to MSGame-OverWatch group

**Comment by Yat3s** [comment]
Close as indexed
