### ISSUE TITLE
[Group Indexing Request] MS 英雄联盟

### ISSUE THREAD

**Issue by Mark9903** [Yat3s/Life-Balance#60]
Please ensure the following requirements before raising your request
- [Yes] This group only serves Microsoft
- [Yes] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS 英雄联盟

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![Lol](https://user-images.githubusercontent.com/39774141/151653830-46f8e6c8-59e8-45f9-abad-e6f32cd3d46f.png)

### City
[苏州/北京/上海]

**Comment by Yat3s** [comment]
Close as indexed.
