### ISSUE TITLE
[Group Indexing Request] MS 霓虹 🇯🇵

### ISSUE THREAD

**Issue by shijieyao** [Yat3s/Life-Balance#61]
Please ensure the following requirements before raising your request
- [x] This group only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS 霓虹 🇯🇵

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![image](https://user-images.githubusercontent.com/22251154/152468349-e8d74677-5098-46d7-a16f-4126276a4902.jpeg)

### City
[苏州/北京/上海]

### Picture for promotion(Optional)

**Comment by shijieyao** [comment]
定位：

分享和畅聊与
日语、日剧、日番、日影、日音（除了 rlgl [Doge]）等一切和日本相关的内容

**Comment by Yat3s** [comment]
Close as indexed.
