### ISSUE TITLE
[Group Indexing Request] MS 尹山湖

### ISSUE THREAD

**Issue by wzw921026** [Yat3s/Life-Balance#63]
Please ensure the following requirements before raising your request
- [Yes ] This group only serves Microsoft
- [Yes] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS 尹山湖

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![ysh](https://user-images.githubusercontent.com/15108642/154892279-56c61153-20c6-4fff-be65-9eb577335dcd.jpg)

### City
苏州

**Comment by Yat3s** [comment]
Close as indexed.
