### ISSUE TITLE
[Group Indexing Request] MS户外群

### ISSUE THREAD

**Issue by yanxurui** [Yat3s/Life-Balance#64]
Please ensure the following requirements before raising your request
- [x] This group only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS户外群

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![image](https://user-images.githubusercontent.com/12461110/155883852-925dfe55-3ed3-4720-b3e3-7f759a50c286.png)

### City
苏州/北京/上海

### 定位

hiking, camping and mountaineering

**Comment by Yat3s** [comment]
Close as indexed.
