### ISSUE TITLE
[Group Indexing Request] MS FF14

### ISSUE THREAD

**Issue by Clounea** [Yat3s/Life-Balance#65]
Please ensure the following requirements before raising your request
- [X] This group only serves Microsoft
- [X] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS FF14

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![FF14-icon (2)](https://user-images.githubusercontent.com/9064823/158322391-178a3969-b61b-4277-a048-89bbd47377d0.jpg)

### City
苏州

### Picture for promotion(Optional)
![FF14-promotion](https://user-images.githubusercontent.com/9064823/158321854-c0b0e1ba-7845-422d-91fe-83003df4d63f.jpg)

**Comment by Yat3s** [comment]
Close as indexed
