### ISSUE TITLE
[Group Indexing Request] MS Coffee

### ISSUE THREAD

**Issue by Zhi-Chen** [Yat3s/Life-Balance#66]
Please ensure the following requirements before raising your request
- [x] This group only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS Coffee

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![5c8f2a741452f](https://user-images.githubusercontent.com/20591532/160238360-29519bc9-3cf7-4a10-90b3-64199a9ecffb.png)

### City
[苏州/北京/上海]

**Comment by Yat3s** [comment]
Close as indexed
