### ISSUE TITLE
[Group Indexing Request] MS Street Dance

### ISSUE THREAD

**Issue by P-Slark** [Yat3s/Life-Balance#67]
Please ensure the following requirements before raising your request
- [x] This group only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS 街舞群

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![image](https://user-images.githubusercontent.com/30462011/161200419-f8127162-9f7a-439d-9031-87cbdf8b7538.png)

### City
[苏州/北京/上海]

**Comment by Yat3s** [comment]
Close as indexed
