### ISSUE TITLE
[Group Indexing Request] Formula one matches watching & discussion 

### ISSUE THREAD

**Issue by DoubleFaults** [Yat3s/Life-Balance#68]
Please ensure the following requirements before raising your request
- [X] This group only serves Microsoft
- [X] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
MS Formula 1

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
![Group icon](https://files.softicons.com/download/web-icons/bees-help-icons-by-artbees/png/128x128/F1-Key-NS.png)

### City
[苏州/北京/上海]

### Picture for promotion(Optional)
![F1](https://www.informatique-mania.com/wp-content/uploads/2021/04/tecla-f1.jpg)

**Comment by Yat3s** [comment]
Close as indexed.
