### ISSUE TITLE
[Group Indexing Request] MS桌上足球

### ISSUE THREAD

**Issue by jacobjiangwei** [Yat3s/Life-Balance#69]
Please ensure the following requirements before raising your request
- [ ] This group only serves Microsoft
- [ ] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
[Group name] MS桌上足球

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
[Group icon]
https://images.squarespace-cdn.com/content/v1/583b4f659de4bb04c55ebafa/1527359302877-5Z6SMJ0MASCDNG27UEVK/05-16+FOOSBALL+FACEBOOK.jpg

### City
[苏州/北京/上海]

**Comment by Yat3s** [comment]
Close as indexed.
