### ISSUE TITLE
[Group Indexing Request] MS Suzhou Toastmaster

### ISSUE THREAD

**Issue by yisuzheng** [Yat3s/Life-Balance#70]
Please ensure the following requirements before raising your request
- [x] This group only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Wechat group

### Group name(displayed on Life Balance)
[Group name] MS Suzhou Toastmaster

### Group icon(File or link, only `.png/.jpg/.jpeg` supported)
[Group icon] https://th.bing.com/th/id/R.9a466e19c747b1aaccdc7ec191597a66?rik=ZXRn%2buuZmaHHyA&riu=http%3a%2f%2fphotos.prnewswire.com%2fprnfull%2f20130222%2fMM64912LOGO&ehk=wZRqlQQRFCa3Kb0KCstRMNyjGKj27MwENBVIn5RJ8a0%3d&risl=&pid=ImgRaw&r=0

### City
[苏州]

**Comment by Yat3s** [comment]
Close as indexed.
