### ISSUE TITLE
Need to delete "欢迎使用富文本编辑器"

### ISSUE THREAD

**Issue by yjhgdipgfj** [Yat3s/Life-Balance#72]
**Describe the bug**
Need to delete "欢迎使用富文本编辑器"

**Screenshots**
![fa8d8fdea00da901b8da74841e167ec](https://user-images.githubusercontent.com/50049070/175868177-bfa450b3-a771-4c51-8898-57f8941da2d8.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 40 Pro
 - OS: HarmonyOS 2.0.0

**Comment by Yat3s** [comment]
Fixed with a default value.
