### ISSUE TITLE
[Add Circle Request] Circle name

### ISSUE THREAD

**Issue by yuzuduan** [Yat3s/Life-Balance#73]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS 飞天拉面

### Circle picture(width:height = 2:1)
![image](https://user-images.githubusercontent.com/108448277/176596732-3816c4ea-9f3b-44ad-86f3-d1f8705884c2.png)

### Tags
文化/美食

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
rAmen

**Comment by Yat3s** [comment]
Close as added.
