### ISSUE TITLE
[Add Circle Request] MS 前端乱炖

### ISSUE THREAD

**Issue by devrsi0n** [Yat3s/Life-Balance#75]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
[MS 前端乱炖]

### Circle picture(width:height = 2:1)
![Frame 1 (1)](https://user-images.githubusercontent.com/7880675/179130451-8deb3ba2-567d-4c2b-86aa-d9f2ca91efb9.png)

### Tags
(eg. 游戏/美食)
前端，技术

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
前端技术分享，交流群

**Comment by devrsi0n** [comment]
@Yat3s I updated the circle picture here.

**Comment by Yat3s** [comment]
Close as added.
