### ISSUE TITLE
[Add Circle Request]ShangHai Frisbee team(一起来玩飞盘吧)

### ISSUE THREAD

**Issue by qfai** [Yat3s/Life-Balance#77]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
ShangHai Frisbee team(一起来玩飞盘吧)

### Circle picture(width:height = 2:1)
https://c8.alamy.com/comp/G27440/ultimate-frisbee-player-G27440.jpg

### Tags
运动，飞盘

### City(Optional)
上海

### Description
常驻地点：上海紫竹 足球场

**Comment by Yat3s** [comment]
Close as added.
