### ISSUE TITLE
[Question] How to add new circle

### ISSUE THREAD

**Issue by hcoona** [Yat3s/Life-Balance#78]
I'm confused by the concept of "Wechat ID". Where can I found the ID? How to associate it with my WeChat group or the bot would help to create a group for the circle? If the latter is correct, why need I input a WeChat ID?

**Comment by Yat3s** [comment]
Hi, @hcoona, Do you mean this Wechat ID?
> invited admin(Wechat ID: 4645643) to Circle's Wechat group

This is an admin's WeChat, you can add this admin as Wechat friend and he will handle all processes of associating your group with Life Balance.

**Comment by hcoona** [comment]
OK, got it. I assume I need to post some "location information" about the WeChat group. But actually, I just need to pull admin into the group, and he would help to finish the onboarding process. Thanks to the great admin.

I suggest opening some process to customer because this workflow not scale. However, currently we have very few onboarding requests, so it's still OK.
