### ISSUE TITLE
[Add Circle Request] MS北京吃喝玩乐

### ISSUE THREAD

**Issue by a1245582339** [Yat3s/Life-Balance#79]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS北京吃喝玩乐

### Circle picture(width:height = 2:1)
![微信截图_20220730203529](https://user-images.githubusercontent.com/30924179/181914534-30bbb11e-8772-4732-a0f4-e0cfe9df37fe.png)

### Tags
北京/吃喝玩乐/综合

### City(Optional)
北京

**Comment by Yat3s** [comment]
@a1245582339 Hi, could you add Wechat **4645643**? Thanks!

**Comment by Yat3s** [comment]
Close as added.
