### ISSUE TITLE
[Add Circle Request] MS CS:GO

### ISSUE THREAD

**Issue by Wei-YB** [Yat3s/Life-Balance#80]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS CS:GO

### Circle picture(width:height = 2:1)
https://github.com/Wei-YB/CSGO-Pic/blob/main/MS-CSGO-pic.png
### Tags
游戏 FPS

### Description(Optional, rich-text supported)
上分？不存在的

**Comment by Yat3s** [comment]
Close as added.
