### ISSUE TITLE
[Add Circle Request] WBA微软分队

### ISSUE THREAD

**Issue by JoanZhou** [Yat3s/Life-Balance#81]
Please ensure the following requirements before raising your request
- [ ] This Circle only serves Microsoft
- [ ] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
WBA微软分队

### Circle picture(width:height = 2:1)
https://www.wakwb.com/t/?extparam=%E5%A5%B3%E7%AF%AE%E5%BC%A0%E8%8C%B9&containerid=1008083e433b5fec3cb9a408dfe73d450f1aff&luicode=10000011&lfid=231522type%3D1%26t%3D10%26q%3D%E5%A5%B3%E7%AF%AE

### Tags
体育

### City(Optional)
北京

### Description(Optional, rich-text supported)
欢迎喜欢打球的女孩

**Comment by Yat3s** [comment]
Close as added.
