### ISSUE TITLE
[Add Circle Request] 微软-上海-Fitness

### ISSUE THREAD

**Issue by LongOddCode** [Yat3s/Life-Balance#82]
Please ensure the following requirements before raising your request
- [√] This Circle only serves Microsoft
- [√] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
微软-上海-Fitness

### Circle picture(width:height = 2:1)
![2-1](https://user-images.githubusercontent.com/71317774/183276622-51a4f230-c77d-42c9-95a0-abed3e0ae842.jpg)

### Description(Optional, rich-text supported)
(e.g. 这个是一个神奇的小圈子)

**Comment by Yat3s** [comment]
Close as added.
