### ISSUE TITLE
[Add Circle Request] MS 围棋

### ISSUE THREAD

**Issue by sunyinkai** [Yat3s/Life-Balance#83]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS 围棋

### Circle picture(width:height = 2:1)
[Circle picture]
![神之一手](https://user-images.githubusercontent.com/29776991/183944975-71fc05f2-7cfc-4f10-b546-e1566250ebc5.png)

### Tags
游戏 棋类

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
坚决要胜 入界宜深
攻彼忘我 弃子另杀
大小都要 逢危就战
爽在轻速 棋都不应
彼强硬搞 势孤玉碎

**Comment by Yat3s** [comment]
Close as added.
