### ISSUE TITLE
[Add Circle Request] MS Early Music

### ISSUE THREAD

**Issue by yuzuduan** [Yat3s/Life-Balance#84]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS Early Music

### Circle picture(width:height = 2:1)
![800px-The_Early_Music_Shop](https://user-images.githubusercontent.com/108448277/185844575-0ab09e38-9042-4adc-bdba-bf2d269ef44d.jpg)

### Tags
音乐/历史

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
中世纪、文艺复兴与巴洛克
讨论、观演与实践

**Comment by Yat3s** [comment]
Close as added.
