### ISSUE TITLE
[Add Circle Request] 微软-北京-Fitness

### ISSUE THREAD

**Issue by OJumpyo** [Yat3s/Life-Balance#85]
Please ensure the following requirements before raising your request
- [√] This Circle only serves Microsoft
- [√] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
[微软-北京-Fitness]

### Circle picture(width:height = 2:1)
[![](http://121.40.89.196:4080/2022/08/2022-08-22-iAQQqXww.png)]

### Tags
(运动/健身)

### City(Optional)
[北京]

### Description(Optional, rich-text supported)
(e.g. 微软北京运动爱好者)

**Comment by Yat3s** [comment]
Close as added.
