### ISSUE TITLE
[Add Circle Request] MS 喷喷喷

### ISSUE THREAD

**Issue by Mev-z** [Yat3s/Life-Balance#86]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS 喷喷喷

### Circle picture(width:height = 2:1)
![splatoon-3 large](https://user-images.githubusercontent.com/14156269/186590547-e65e8711-678d-4d27-b1a7-72358e656e58.jpg)

### Tags
游戏
splatoon3

### City(Optional)
/

### Description(Optional, rich-text supported)
乌贼章鱼来涂地

**Comment by Yat3s** [comment]
Close as added.
