### ISSUE TITLE
[Add Circle Request] 再就业

### ISSUE THREAD

**Issue by sakamoto-poteko** [Yat3s/Life-Balance#87]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
再就业

### Circle picture(width:height = 2:1)
![再就业](https://user-images.githubusercontent.com/4940216/187137527-a4f68682-62a9-4394-9676-a123ed10b1be.png)

### Tags
再就业

### City(Optional)
苏州

### Description(Optional, rich-text supported)
咱们工人有力量

**Comment by Yat3s** [comment]
Close as added.
