### ISSUE TITLE
[Add Circle Request] MS 魔方吧

### ISSUE THREAD

**Issue by yzffvinz** [Yat3s/Life-Balance#88]
Please ensure the following requirements before raising your request
- [X] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
[Circle name]
MS 魔方吧
### Circle picture(width:height = 2:1)
![002](https://user-images.githubusercontent.com/31758094/190306369-c7d97ac4-b7f5-4092-9462-1a132d80518a.jpg)

### Tags
魔方/桌游

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
魔方交流教学收藏等与魔方相关的一切！

**Comment by Yat3s** [comment]
Close as added.
