### ISSUE TITLE
微软苏州网球

### ISSUE THREAD

**Issue by ellie-mac** [Yat3s/Life-Balance#89]
Please ensure the following requirements before raising your request
- [ ] This Circle only serves Microsoft
- [ ] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
微软苏州网球

### Circle picture(width:height = 2:1)
![image](https://user-images.githubusercontent.com/50949485/189308890-f647b590-7369-4aa7-9472-5532b8d71363.png)

### Tags
网球/运动

### City(Optional)
[苏州]

### Description(Optional, rich-text supported)
网球爱好者约球群

**Comment by Yat3s** [comment]
Hi @ellie-mac, Could you add me to your Wechat Group? My Wechat ID: 4645643

**Comment by Yat3s** [comment]
@ellie-mac Close as we already have a tennis circle.
