### ISSUE TITLE
[Add Circle Request] MS 玄学研究

### ISSUE THREAD

**Issue by edwardzhengsiyuan** [Yat3s/Life-Balance#90]
Please ensure the following requirements before raising your request
- [ ] This Circle only serves Microsoft
- [ ] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS 玄学研究

### Circle picture(width:height = 2:1)
![新建项目 (2)](https://user-images.githubusercontent.com/33859175/190098682-98823942-751f-4819-9ab8-4feacc9f3e9a.jpg)

### Tags
命理 占卜 堪舆 相术

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
欢迎各位对玄学有一定基础或者感兴趣的小伙伴加入讨论.
命理：四柱八字，紫微斗数，占星星盘，铁板神数，七政四余……
占卜：纳甲筮法，梅花易数，塔罗，大六壬……
堪舆：
相术：
其他：阿卡西记录，星体投射……
……
欢迎补充

**Comment by Yat3s** [comment]
@edwardzhengsiyuan Hi, could you add me to your Wechat Group? My Wechat ID: 4645643

**Comment by Yat3s** [comment]
Close as added.
