### ISSUE TITLE
[Add Circle Request] MS炉石传说

### ISSUE THREAD

**Issue by sixG-old** [Yat3s/Life-Balance#91]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MS炉石传说

### Circle picture(width:height = 2:1)
![炉石-2-1](https://user-images.githubusercontent.com/101958786/190383589-d41f4c25-c860-4bd2-ae1a-cc588b39ab28.jpg)

### Tags
游戏

### City(Optional)
苏州

### Description(Optional, rich-text supported)
小伙子们，看看谁来了。
留个位子出来，外面太冷了。

**Comment by Yat3s** [comment]
@sixG-old Hi, could you add me to your Wechat Group? My Wechat ID: 4645643

**Comment by Yat3s** [comment]
Close as added.
