### ISSUE TITLE
[Add Circle Request] MSCNDota

### ISSUE THREAD

**Issue by sixG-old** [Yat3s/Life-Balance#92]
Please ensure the following requirements before raising your request
- [x] This Circle only serves Microsoft
- [x] Invited admin(Wechat ID: **4645643**) to Circle's Wechat group

### Circle name(displayed on Life Balance)
MSCNDota

### Circle picture(width:height = 2:1)
![Dota不朽盾](https://user-images.githubusercontent.com/101958786/190384881-8a30293c-3cfb-42e4-bdd5-09cc246350ad.jpg)

### Tags
游戏/刀塔

### City(Optional)
苏州

### Description(Optional, rich-text supported)
当你被对面杀得生活不能自理的时候，想想原因，别死了就TP过去。

**Comment by Yat3s** [comment]
@sixG-old Hi, could you add me to your Wechat Group? My Wechat ID: 4645643

**Comment by Yat3s** [comment]
Close as added.
