### ISSUE TITLE
[Add Circle Request]  MS咖啡师再就业

### ISSUE THREAD

**Issue by stwwrong** [Yat3s/Life-Balance#93]
# You must know!
Please invited admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
咖啡师再就业

### Circle picture(width:height = 2:1)
![1](https://user-images.githubusercontent.com/65069276/192443197-933a0fa2-6ac2-45c8-84e7-2a66ae9b34c9.jpg)

### Tags
再就业

### City(Optional)
苏州

### Description(Optional, rich-text supported)
一起签订契约（不是）成为咖啡师吧

**Comment by Yat3s** [comment]
Close as added.
