### ISSUE TITLE
[Add Circle Request] MS Lego

### ISSUE THREAD

**Issue by haochenxie20** [Yat3s/Life-Balance#94]
# You must know!
Please invited admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
[Circle name]

MS Lego乐高

### Circle picture(width:height = 2:1)
[Circle picture]
![image](https://user-images.githubusercontent.com/107969528/192680024-76de0ffa-4370-4569-bac1-efd2c6819301.png)

### Tags
(eg. 游戏/美食)
娱乐/购物？

### City(Optional)
[苏州/北京/上海]
苏州

### Description(Optional, rich-text supported)
(e.g. 这个是一个神奇的小圈子)
MS乐高玩家聚集地，官套推荐，moc经验分享，团购(重点）

**Comment by Yat3s** [comment]
Close as added.
