### ISSUE TITLE
[Add Circle Request] M$ SH 狼人杀

### ISSUE THREAD

**Issue by jiashun0011** [Yat3s/Life-Balance#95]
# You must know!
Please invited admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
M$ SH 狼人杀

### Circle picture(width:height = 2:1)
![msww](https://user-images.githubusercontent.com/11517839/192695552-b25ef86c-c479-4c00-a2b5-2ef249026be6.png)

### Tags
游戏/桌游

### City(Optional)
上海

### Description(Optional, rich-text supported)
M$ 狼人杀爱好者聚集地，线上/线下狼人杀活动组织。

**Comment by Yat3s** [comment]
Close as added
