### ISSUE TITLE
[Add Circle Request] MS 西点师再就业

### ISSUE THREAD

**Issue by BATTERIA** [Yat3s/Life-Balance#96]
# You must know!
Please invited admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
MS 西点师再就业

### Circle picture(width:height = 2:1)
![2681665198977_ pic_hd](https://user-images.githubusercontent.com/29327829/194685480-acc922e8-06aa-4b9c-818a-785d769af7d1.jpg)

### Tags
再就业/美食

### City(Optional)
[苏州]

### Description(Optional, rich-text supported)
欢迎喜欢做西点的小伙伴，烘焙爱好者联盟在此。可以组团报考中级高级西点师，政府全额补贴学费。

**Comment by Yat3s** [comment]
Close as added.
