### ISSUE TITLE
[Add Circle Request] 微软看球群👀⚽️

### ISSUE THREAD

**Issue by sangle7** [Yat3s/Life-Balance#98]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
微软看球群 👀⚽️

### Circle picture(width:height = 2:1)
![Circle picture](https://assets3.thrillist.com/v1/image/2765103/792x528/scale;webp=auto;jpeg_quality=60;progressive.jpg)

### Tags
足球

### City(Optional)
[苏州/北京/上海]

### Description(Optional, rich-text supported)
一个看足球&聊球的群

**Comment by Yat3s** [comment]
Close as added.
