### ISSUE TITLE
[Add Circle Request] 苏州辣王之王

### ISSUE THREAD

**Issue by guojms** [Yat3s/Life-Balance#99]
# You must know!
Please invite admin(Wechat ID: **4645643**) to Circle's Wechat group before raising your request

### Circle name(displayed on Life Balance)
苏州辣王

### Circle picture(width:height = 2:1)
![image](https://user-images.githubusercontent.com/87634713/196623601-d05968b2-086f-4e38-8f7b-ced5e5b6d34e.png)
### Tags
(eg. 游戏/美食)

### City(Optional)
[苏州]

### Description(Optional, rich-text supported)
关于辣的一切 吃辣爱好者

**Comment by Yat3s** [comment]
Close as added.
